Add CSI Plug-N-Play Design
sodafoundation/architecture-analysis pull request #73
Opened 2020-09-20 05:24 UTC by asifdxtreme

**What type of PR is this?**

/kind new feature

**What this PR does / why we need it**:
This PR adds the design of new CSI Plug-N-Play mechanism

2020-09-20 05:39 UTC, asifdxtreme commented
/cc @kumarashit @skdwriting

2020-09-21 10:58 UTC, kumarashit approved these changes
LGTM

2020-09-21 11:10 UTC, skdwriting reviewed
1) Please add the current SODA NBP for CSI and difference aspects
2) Also clearly mention the issues on the API flow (horizontally to SODA)
3) Also mention, we will have the current CSI and this design for exploration and testing and finalize one design which is better. So the refactoring is expected

2020-09-21 12:29 UTC, asifdxtreme commented
> 1. Please add the current SODA NBP for CSI and difference aspects
> 2. Also clearly mention the issues on the API flow (horizontally to SODA)
> 3. Also mention, we will have the current CSI and this design for exploration and testing and finalize one design which is better. So the refactoring is expected

@skdwriting Done. Added all the details in the design docs

2020-09-22 03:49 UTC, skdwriting requested changes
Can we update the existing design document and add the new approach as an alternate design.
Then we provide pros/cons and conclude accordingly.
Otherwise, it will create duplicate design docs for CSI plug and play

2020-09-24 09:36 UTC, asifdxtreme commented
> Can we update the existing design document and add the new approach as an alternate design.
> Then we provide pros/cons and conclude accordingly.
> Otherwise, it will create duplicate design docs for CSI plug and play

@skdwriting I have updated the PR with actual design and an alternate design , [preview :](https://github.com/asifdxtreme/design-specs/tree/master/specs/csi-plug-n-play)

2020-09-29 18:50 UTC, skdwriting commented on specs/csi-plug-n-play/Readme.md
> +# SODA-CSI Plug-N-Play
Original file history lost.
Can we make the design document as a design document name?
Also the alternate, if you want a separate file, please name it accordingly and link. Need to cross link both doc.
Else, update the original and avoid the duplicate information. (intro, goals etc...)

2021-06-04 07:42 UTC, skdwriting commented
@asifdxtreme as we discussed please raise a new PR

2021-06-04 07:42 UTC, closed without merging